apiVersion: v1
kind: DaemonSet
metadata:
  name: "{{ app_name }}"
  namespace: "{{ namespace }}"
spec:
  selector:
    matchLabels:
      name: '{{ app_name }}'
  template:
    metadata:
      labels:
        name: "{{ app_name }}"
    spec:
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: openshift.com/gpu-accelerator
                operator: Exists
      serviceAccount: "{{ app_name }}"
      serviceAccountName: "{{ app_name }}"
      hostNetwork: true
      hostPID: true
      containers:
      - image: "{{ nvidia_image_name }}:{{ nvidia_image_tag }}"
        name: "{{ app_name }}"
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins