- name: set up authentication and project
  hosts: localhost
  gather_facts: false
  connection: local
  become: no

  roles:
    - oatakan.openshift-add-auth-config
    - role: openshift-project-nvidia
      action: provision