- name: set up authentication and project
  hosts: localhost
  gather_facts: false
  connection: local
  become: no

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: openshift-project-nvidia
      action: provision