- hosts: nodes,tag_app_name_ai_deoldify
  become: yes
  tasks:
    - name: check to see if NVIDIA GPU is present
      shell: lspci -v -s $(lspci | grep ' VGA ' | grep NVIDIA | cut -d" " -f 1 | head -1) | grep NVIDIA
      register: check_gpu_present
      no_log: yes
      ignore_errors: yes

    - block:
        - name: check if the installation and drivers are working
          shell: nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g'
          register: nvidia_smi_command

        - name: debug nvidia_smi command output
          debug:
            var: nvidia_smi_command.stdout

        - name: fail if no output
          fail:
            msg: "nvidia_smi is not installed successfully."
          when: nvidia_smi_command.stdout == ""

      when: check_gpu_present is success

    - block:
        - name: test cuda-vector-add container
          docker_container:
            name: test-cuda-vector-add
            image: docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
            #auto_remove: yes
            interactive: yes
            detach: no
          register: cuda_vector_add_container

        - name: debug cuda_vector_add_container output
          debug:
            var: cuda_vector_add_container.ansible_facts.docker_container.Output

        - name: remove test cuda-vector-add container
          docker_container:
            name: "{{ cuda_vector_add_container.ansible_facts.docker_container.Id | default('test-cuda-vector-add') }}"
            state: absent

      when: check_gpu_present is success