- hosts: nodes
  become: yes
  tasks:
    - name: check to see if NVIDIA GPU is present
      shell: lspci -v -s $(lspci | grep ' VGA ' | grep NVIDIA | cut -d" " -f 1 | head -1) | grep NVIDIA
      register: check_gpu_present
      ignore_errors: yes

    - block:
        - name: test cuda-vector-add container
          docker_container:
            name: test-cuda-vector-add
            image: docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
            #auto_remove: yes
            interactive: yes
            detach: no
          register: cuda_vector_add_container

        - name: debug cuda_vector_add_container output
          debug:
            var: cuda_vector_add_container.ansible_facts.docker_container.Output

        - name: remove test cuda-vector-add container
          docker_container:
            name: "{{ cuda_vector_add_container.ansible_facts.docker_container.Id | default('test-cuda-vector-add') }}"
            state: absent

      when: check_gpu_present is success