- hosts: nodes
  become: yes
  roles:
    - nvidia-driver
    - { role: nvidia-container-runtime-hook, when: gpu_present }
    - { role: openshift-gpu-device-plugin, when: gpu_present }

- name: add cluster admin user
  hosts: masters
  become: yes
  tasks:
    - name: assign cluster admin role to admin user
      command: oc adm policy add-cluster-role-to-user cluster-admin admin
      run_once: yes

- name: label nodes
  hosts: localhost
  gather_facts: false
  connection: local
  become: no
  vars:
    namespace: default

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no

  post_tasks:
    #- name: label nodes
    #  k8s_v1_node:
    #    name: "{{ item }}"
    #    labels:
    #      openshift.com/gpu-accelerator=true
    #  environment:
    #    K8S_AUTH_KUBECONFIG: 'config'
    #  with_items: "{{ groups.nodes }}"

    - name: label nodes
      command: oc label node --config='{{ oc_config_file_location }}' --overwrite=true {{ item }} openshift.com/gpu-accelerator=true
      with_items: "{{ groups.nodes }}"
      when: (hostvars[item].gpu_present) and (hostvars[item].cuda_vector_add_container is defined) and ("Test PASSED" in hostvars[item].cuda_vector_add_container.ansible_facts.docker_container.Output)