- hosts: nodes
  become: yes
  roles:
    - nvidia-driver
    - nvidia-container-runtime-hook

- name: label nodes
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - oatakan.openshift-add-auth-config

  post_tasks:
    - name: label nodes
      command: oc label node --config='{{ oc_config_file_location }}' {{ item }} openshift.com/gpu-accelerator=true
      with_items: "{{ groups.nodes }}"
      when: (item.cuda_vector_add_container is defined) and (item.cuda_vector_add_container is success)
