- hosts: skip
  become: yes
  roles:
    - nvidia-driver
    - nvidia-container-runtime-hook
    - openshift-gpu-device-plugin

- name: label nodes
  hosts: localhost
  gather_facts: false
  connection: local
  become: no
  vars:
    namespace: default

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no

  post_tasks:
    - name: label nodes
      k8s_v1_node:
        name: "{{ item }}"
        labels:
          openshift.com/gpu-accelerator: true
      with_items: "{{ groups.nodes }}"

    #- name: label nodes
    #  command: oc label node --config='{{ oc_config_file_location }}' {{ item }} openshift.com/gpu-accelerator=true
    #  with_items: "{{ groups.nodes }}"
    #  when: (hostvars[item].cuda_vector_add_container is defined) and ("Test PASSED" in hostvars[item].cuda_vector_add_container.ansible_facts.docker_container.Output)
