- hosts: nodes
  become: yes
  roles:
    - nvidia-driver
    - { role: nvidia-container-runtime-hook, when: gpu_present|bool }
    #- { role: openshift-gpu-device-plugin, when: gpu_present }

- name: add cluster admin user
  hosts: masters
  become: yes
  tasks:
    - name: assign cluster admin role to admin user
      shell: oc login -u system:admin && oc adm policy add-cluster-role-to-user cluster-admin admin
      run_once: yes
      ignore_errors: yes

- name: label nodes
  hosts: localhost
  gather_facts: false
  connection: local
  become: no
  vars:
    namespace: default

  roles:
    - role: oatakan.openshift-add-auth-config
      oc_auth_type: api

  post_tasks:
    #- name: label nodes
    #  k8s_v1_node:
    #    name: "{{ item }}"
    #    labels:
    #      openshift.com/gpu-accelerator=true
    #  environment:
    #    K8S_AUTH_KUBECONFIG: 'config'
    #  with_items: "{{ groups.nodes }}"

#    - name: label nodes
#      command: oc label node --config='{{ oc_config_file_location }}' --overwrite=true {{ item }} openshift.com/gpu-accelerator=true
#      loop: "{{ groups.nodes }}"
#      when:
#        - hostvars[item].gpu_present|bool
#        - hostvars[item].cuda_vector_add_container is defined
#        - ("Test PASSED" in hostvars[item].cuda_vector_add_container.ansible_facts.docker_container.Output)

    - name: label nodes
      k8s:
        state: present
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              openshift.com/gpu-accelerator: "true"
        validate_certs: no
        api_key: "{{ api_key }}"
      loop: "{{ groups.nodes }}"
      when:
        - hostvars[item].gpu_present|bool
        - hostvars[item].cuda_vector_add_container is defined
        - ("Test PASSED" in hostvars[item].cuda_vector_add_container.ansible_facts.docker_container.Output)