- name: undeploy
  hosts: localhost
  gather_facts: false
  connection: local
  become: no
  vars:
    namespace: nvidia

  pre_tasks:
    - name: authenticate with cluster
      include_role:
        name: oatakan.openshift-add-auth-config
      vars:
        oc_auth_type: api

  roles:
    - role: openshift-project-nvidia
      apb_action: deprovision
      playbook_debug: false

  post_tasks:
    - name: delete project
      k8s:
        name: '{{ namespace }}'
        api_version: v1
        kind: Project
        validate_certs: no
        api_key: "{{ api_key }}"
        state: absent
      when: "'kube-system' not in namespace"