- name: provision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: oatakan.openshift-add-auth-config
    oc_auth_type: api
  - role: ../../.
  vars:
    apb_action: provision