- name: install pciutils
  yum:
    name: pciutils
    state: present

- name: check to see if NVIDIA GPU is present
  shell: lspci  -v -s  $(lspci | grep ' VGA ' | grep NVIDIA | cut -d" " -f 1 | head -1) | grep NVIDIA
  register: check_gpu_present
  ignore_errors: yes

- name: set gpu present
  set_fact:
    gpu_present: yes
  when: check_gpu_present is success

- name: set gpu not present
  set_fact:
    gpu_present: no
  when: check_gpu_present is not success

- name: install if NVIDIA GPU is present
  include_tasks: install_driver.yml
  when: check_gpu_present is success

