---
- name: install nvidia-container-runtime repo
  get_url:
    url: "{{ nvidia_container_runtime_repo_url }}"
    dest: /etc/yum.repos.d/nvidia-container-runtime.repo

# this doesn't seem to work
- name: import nvidia repo key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ nvidia_container_runtime_repo_keys }}"

- name: disable gpg key check on the nvidia repo
  replace:
    path: /etc/yum.repos.d/nvidia-container-runtime.repo
    regexp: repo_gpgcheck=1
    replace: repo_gpgcheck=0

- name: install nvidia-container-runtime-hook
  yum:
    name: nvidia-container-runtime-hook
    state: present

- name: import openshift oci hook
  import_tasks: oci_hook.yml
  when: openshift_oci_hook_install | bool

- block:
    - name: test cuda-vector-add container
      docker_container:
        name: test-cuda-vector-add
        image: docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
        #auto_remove: yes
        interactive: yes
        detach: no
      register: cuda_vector_add_container

  rescue:
    - name: reboot the system
      reboot:

    - name: retry testing cuda-vector-add container
      docker_container:
        name: test-cuda-vector-add
        image: docker.io/mirrorgooglecontainers/cuda-vector-add:v0.1
        #auto_remove: yes
        interactive: yes
        detach: no
      register: cuda_vector_add_container

  always:
    - name: debug cuda_vector_add_container output
      debug:
        var: cuda_vector_add_container.ansible_facts.docker_container.Output
      when:
        - cuda_vector_add_container is defined
        - cuda_vector_add_container.ansible_facts.docker_container.Output is defined

    - name: remove test cuda-vector-add container
      docker_container:
        name: "{{ cuda_vector_add_container.ansible_facts.docker_container.Id | default('test-cuda-vector-add') }}"
        state: absent

- name: fail if not the expected output
  fail:
    msg: "nvidia-container-runtime is not installed successfully."
  when:
    - cuda_vector_add_container.ansible_facts.docker_container.Output is defined
    - ("Test PASSED" not in cuda_vector_add_container.ansible_facts.docker_container.Output)