---

- name: "Set objects state={{ state }}"
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
    validate_certs: no
    api_key: "{{ api_key }}"
  loop:
    - service_account.yml
    - scc.yml
    - daemon_set.yml