---
- name: create project from namespace
  openshift_v1_project:
    name: '{{ namespace }}'
    state: present
  environment:
    K8S_AUTH_KUBECONFIG: 'config'

- name: create ServiceAccount
  k8s_v1_service_account:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
  environment:
    K8S_AUTH_KUBECONFIG: 'config'

- name: process scc object template
  template:
    src: scc.yml.j2
    dest: "/tmp/scc.yml"
  register: scc_object

- set_fact:
    scc_object_path: "{{ scc_object.dest | default(scc_object.path) }}"

- name: create scc
  command: "oc create --config='{{ oc_config_file_location }}' -f {{ scc_object_path }} -n {{ namespace }}"
  ignore_errors: yes


#- name: deploy scc
#  openshift_raw:
#    name: "{{ application_name }}"
#    state: present
#    definition: "{{ lookup('template', item) | from_yaml }}"
#  with_items:
#    - scc.yml
#  environment:
#    K8S_AUTH_KUBECONFIG: 'config'

- name: deploy daemonset
  k8s:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    definition: "{{ lookup('template', item) | from_yaml }}"
    verify_ssl: no
    api_key: "{{ api_key }}"
  with_items:
    - daemon_set.yml
  environment:
    K8S_AUTH_KUBECONFIG: 'config'