---
- name: create project from namespace
  openshift_v1_project:
    name: '{{ namespace }}'
    state: present
  environment:
    K8S_AUTH_KUBECONFIG: 'config'

- name: create ServiceAccount
  k8s_v1_service_account:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present

- name: create scc
  openshift_v1_security_context_constraints:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    allow_host_dir_volume_plugin: yes
    allow_host_ipc: yes
    allow_host_network: yes
    allow_host_pid: yes
    allow_host_ports: yes
    allow_privileged_container: yes
    allowed_capabilities:
      - '*'
    fs_group_type: RunAsAny
    groups:
      - system:cluster-admins
      - system:nodes
      - system:masters
    metadata:
      name: "{{ application_name }}-scc"
    priority: 10
    read_only_root_filesystem: no
    run_as_user:
      type: RunAsAny
    se_linux_context:
      type: RunAsAny
    seccomp_profiles:
      - '*'
    supplemental_groups:
      type: RunAsAny
    users:
      - system:serviceaccount:nvidia:nvidia-deviceplugin
    volumes:
      - '*'

- name: deploy daemonset
  k8s_v1beta1_daemon_set:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    metadata:
      name: "{{ application_name }}"
      namespace: "{{ namespace }}"
    spec_template_metadata_labels:
      name: "{{ application_name }}"
    spec_template_spec_priority_class_name: system-node-critical
    spec_template_spec_affinity_node_affinity_required_during_scheduling_ignored_during_execution_node_selector_terms:
      - key: openshift.com/gpu-accelerator
        operator: Exists
    spec_template_spec_service_account: "{{ application_name }}"
    spec_template_spec_service_account_name: "{{ application_name }}"
    spec_template_spec_host_network: yes
    spec_template_spec_host_pid: yes
    containers:
      - image: "{{ container_image_name }}"
        name: "{{ application_name }}"
        volume_mounts:
          - mount_path: /var/lib/kubelet/device-plugins
            name: device-plugin
    volumes:
      - name: device-plugin
        host_path:
          path: /var/lib/kubelet/device-plugins