- name: read node-config.yaml
  slurp:
    src: /etc/origin/node/node-config.yaml
  register: node_config_file

- name: set node_config variable
  set_fact:
    node_config: "{{ node_config_file['content'] | b64decode }}"

- name: add to kubuletarguments to node-config
  set_fact:
    node_config: "{{ node_config_file|combine(kubeletArguments, recursive=True) }}"

- debug:
    msg: "{{ node_config }}"