- name: read node-config.yaml
  slurp:
    src: /etc/origin/node/node-config.yaml
  register: node_config_file

- name: set node_config variable
  set_fact:
    node_config: "{{ node_config_file['content'] | b64decode | from_yaml }}"

- name: add to kubuletarguments to node-config
  set_fact:
    node_config: "{{ node_config|combine(node_config_add_variable, recursive=True) }}"

- name: write the updated node-config file
  template:
    src: node-config.yaml.j2
    dest: /etc/origin/node/node-config.yaml
    backup: yes

- name: test if origin node
  command: systemctl status origin-node
  register: origin_node
  ignore_errors: yes

- name: restart openshift node
  service:
    name: atomic-openshift-node
    state: restarted
  when: origin_node is not success

- name: restart origin node
  service:
    name: origin-node
    state: restarted
  when: origin_node is success