---

- name: Add repo
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: '{{ nvidia_gpu_operator_git_url }}'

- name: deploy nvidia-gpu-operator
  kubernetes.core.helm:
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    chart_version: "{{ nvidia_gpu_operator_version }}"
    release_namespace: "{{ gpu_operator_namespace }}"
    values: "{{ lookup('template', 'input_vars.yml.j2') | from_yaml }}"
    update_repo_cache: yes
    kubeconfig: /root/{{ cluster_id }}/auth/kubeconfig
  ignore_errors: yes