---

- name: create namespace file
  template:
    src: namespace.yml.j2
    dest: /root/{{ cluster_id }}/gpu-operator-namespace.yml

- name: ensure namespace exists
  shell: oc --kubeconfig auth/kubeconfig apply -f gpu-operator-namespace.yml --wait
  args:
    chdir: /root/{{ cluster_id }}/
  register: ocp_gpu_namespace_create
  until: ocp_gpu_namespace_create is success
  retries: 30
  delay: 5

- include_tasks: okd.yml
  when: ocp_type == 'okd'

- include_tasks: helm.yml
  when:
    - ocp_version is version('4.10', '<') or ocp_type == 'okd'

- include_tasks: operator.yml
  when:
    - ocp_type == 'enterprise'
    - ocp_version is version('4.10', '>=')

- name: wait for nvidia-driver-validator pod to be created
  shell: oc --kubeconfig auth/kubeconfig get pods -n {{ gpu_operator_namespace }} -l 'app=nvidia-device-plugin-validator' -oname
  args:
    chdir: /root/{{ cluster_id }}/
  register: oc_get_driver_validator_pod_name
  until:
    - oc_get_driver_validator_pod_name is success
    - oc_get_driver_validator_pod_name.stdout != ''
  retries: 50
  delay: 30

- name: wait for nvidia-driver-validator pod to finish
  shell: oc --kubeconfig auth/kubeconfig get {{ oc_get_driver_validator_pod_name.stdout }} -n {{ gpu_operator_namespace }} -o jsonpath='{.status.phase}'
  args:
    chdir: /root/{{ cluster_id }}/
  register: oc_get_driver_validator_pod
  until:
    - oc_get_driver_validator_pod is success
    - oc_get_driver_validator_pod.stdout == 'Succeeded' or oc_get_driver_validator_pod.stdout == 'Failed'
  retries: 50
  delay: 30

- name: drive validator status
  debug:
    msg: "Driver validator status: {{ oc_get_driver_validator_pod.stdout }}"