---

- name: ensure go-toolset is installed
  package:
    name: go-toolset

- name: check out from git
  git:
    repo: '{{ sro_git_url }}'
    dest: /tmp/special-resource-operator
    version: "{{ sro_image_tag }}"

#- name: expose registry to outside
#  shell: oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
#  environment:
#    KUBECONFIG: /root/{{ cluster_id }}/auth/kubeconfig
#
#- name: get default route to registry
#  shell: oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}'
#  environment:
#    KUBECONFIG: /root/{{ cluster_id }}/auth/kubeconfig
#  register: oc_registry_default_route
#
#- name: login with podman
#  shell: podman login -u $(oc whoami) -p $(oc whoami -t) --tls-verify=false {{ oc_registry_default_route.stdout }}
#  environment:
#    KUBECONFIG: /root/{{ cluster_id }}/auth/kubeconfig

- name: create sro buildconfig file
  template:
    src: "{{ item }}"
    dest: /root/{{ cluster_id }}/{{ item | replace('.j2','') }}
  loop:
    - namespace.yml.j2
    - sro-buildconfig.yml.j2

- name: ensure namespace exists
  shell: oc --kubeconfig auth/kubeconfig apply -f namespace.yml --wait
  args:
    chdir: /root/{{ cluster_id }}/
  register: ocp_sro_namespace_create
  until: ocp_sro_namespace_create is success
  retries: 30
  delay: 5

- name: apply sro buildconfig
  shell: oc --kubeconfig auth/kubeconfig apply -f sro-buildconfig.yml -n "{{ namespace }}" --wait
  args:
    chdir: /root/{{ cluster_id }}/
  register: ocp_sro_buildconfig_create
  until: ocp_sro_buildconfig_create is success
  retries: 30
  delay: 5

- name: change nvidia-driver build url
  replace:
    path: /tmp/special-resource-operator/recipes/nvidia-gpu/manifests/0000-state-driver-buildconfig.yaml
    regexp: '(\s+uri\: ).*?$'
    replace: '\1{{ sro_nvidia_driver_build_config_repo }}'
  ignore_errors: yes

- name: change nvidia-driver version
  replace:
    path: /tmp/special-resource-operator/recipes/nvidia-gpu/manifests/0000-state-driver-buildconfig.yaml
    regexp: '(\s+value\: )\"440\.33\.01\".*?$'
    replace: '\1\\"{{ sro_nvidia_driver_build_config_repo }}\\"'
  ignore_errors: yes

- name: deploy sro
  shell: make deploy
  args:
    chdir: /tmp/special-resource-operator
  environment:
    KUBECONFIG: /root/{{ cluster_id }}/auth/kubeconfig
    PULLPOLICY: Always
    REGISTRY: image-registry.openshift-image-registry.svc:5000
    ORG: "{{ namespace }}"
    NAMESPACE: "{{ namespace }}"
    TAG: "{{ sro_image_tag }}"
  register: deploy_sro

- debug:
    msg: "{{ deploy_sro.stdout }}"
